# Description:
# Bazel macros used by projects.

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

exports_files(
    [
        "tf_macros.bzl",
    ],
)
